name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
        with:
          fetch-depth: 0

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v5.2.1
        id: version
        with:
          major_pattern: "major:"
          minor_pattern: "feat:"
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"

      - name: "Login con dockerhub"
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

        run: |
          echo "Login con dockerhub 🔥"
          docker login -u $DOCKER_USER -p $DOCKER_PASS
      
      - name: "Build image"
        env:
          VERSION: ${{steps.version.outputs.version}}
        run: |
          echo "Build image 🐳"
          docker build -t epmyas2022/mountains:$VERSION . 
          echo "Version de imagen $VERSION"

      - name: "Push image"
        env:
          VERSION: ${{steps.version.outputs.version}}
        run: |
          echo "Push image  🐳"
          docker push epmyas2022/mountains:$VERSION

        #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
